#!/bin/bash

#----------------------------------------------------------------------------------------------------

function PrintUsage()
{
	echo -e "USAGE: run <option> <src file> <option> <dir> <dir> ..."
	echo -e "OPTIONS"

	echo -e "	-h, --help		print this help and exit"
	echo -e "	-no-run, -dno		do not run the program for any diagonal, just compile"
	echo -e "	-d45b_56t, -d45b	run the program for diagonal 45b-56t"
	echo -e "	-d45t_56b, -d45t	run the program for diagonal 45t-56b"
	echo -e "	-dboth			run the program for both diagonals"
	echo -e "	-dc, -dcomb		run the program in combined diagonals"
	echo -e "	-danti			run the program in anti-diagonals"
	echo -e "	-O <option>		pass the option to the program"
	echo -e "	-no-bckg		do no run compilation and programs in background"
}

#----------------------------------------------------------------------------------------------------

diag_45b_56t="y"
diag_45t_56b="y"
diag_combined="y"

diag_45b_56b="n"
diag_45t_56t="n"

runInBackground="y"

rcIncompatibleDiagonal=123

#----------------------------------------------------------------------------------------------------

function RunOneDiagonal()
{
	local tag="$1"
	local dir="$2"
	local par_more="$3"
	local diag="$4"
	local options="$5"

	local optionsStr=""
	if [ ! "$options" == "" ]
	then
		optionsStr=" ($options)"
	fi

	label="$tag @ $dir:$diag"
	log="${tag}_${diag}.log_run"

	echo "$label > running$optionsStr"
	"./$exe_file" "$diag" $options &> "$log"
	errCode="$?"
	case "$errCode" in
		0)
			echo "$label > done"
			;;

		$rcIncompatibleDiagonal)
			rm "$log"
			;;

		*)
			echo "$label > run error ($errCode)"
			if [ "$par_more" -eq 1 ]; then tail -n 5 "$log"; fi
			;;
	esac
}

#----------------------------------------------------------------------------------------------------

function RunOneDir()
{
	local input="$1"
	local src_file=".$input"
	local tag="${input%.*}"
	local exe_file=".$tag"
	local dir="$2"
	local par_more="$3"
	local options="$4"

	local top_dir=`pwd`

	cp "$input" "$dir/$src_file"
	cd "$dir"
	
	echo "$tag @ $dir > compiling"
	g++ -O3 -Wall -Wextra --std=c++11\
			-I"$top_dir" \
			`root-config --libs` -lMinuit -lMinuit2 `root-config --cflags` \
			-I"$CMSSW_BASE/src" \
			-I"/afs/cern.ch/cms/slc6_amd64_gcc481/external/fastjet/3.0.3/include" \
			-L"$CMSSW_BASE/lib/slc6_amd64_gcc481" \
			-lTotemAnalysisTotemNtuplizer \
			"$src_file" -o "$exe_file" &> "$tag.log_compile"

	# compilation error?
 	if [ $? -ne 0 ]
	then
		echo "$tag @ $dir > error in compilation"
		if [ "$par_more" -eq 1 ]; then cat "$tag.log_compile"; fi
		return
	else
		echo "$tag @ $dir > compiled"
	fi

	if [ ! -s "$tag.log_compile" ]
	then
		rm "$tag.log_compile"
	fi

	# run
	if [ "$diag_45b_56t" == "y" ]
	then
		RunOneDiagonal "$tag" "$dir" "$par_more" "45b_56t" "$options" &
	fi

	if [ "$diag_45t_56b" == "y" ]
	then
		RunOneDiagonal "$tag" "$dir" "$par_more" "45t_56b" "$options" &
	fi
	
	if [ "$diag_combined" == "y" ]
	then
		RunOneDiagonal "$tag" "$dir" "$par_more" "combined" "$options" &
	fi

	if [ "$diag_45b_56b" == "y" ]
	then
		RunOneDiagonal "$tag" "$dir" "$par_more" "45b_56b" "$options" &
	fi

	if [ "$diag_45t_56t" == "y" ]
	then
		RunOneDiagonal "$tag" "$dir" "$par_more" "45t_56t" "$options" &
	fi
}

#----------------------------------------------------------------------------------------------------

if [ $# -le 0 ]
then
	PrintUsage
	exit 1
fi

while [ -n "$1" ]
do
	case "$1" in
		"-h" | "--help")
			PrintUsage
			exit 1
			;;

		"-no-run" | "-dno")
			diag_45b_56t="n"
			diag_45t_56b="n"
			diag_combined="n"
			diag_45b_56b="n"
			diag_45t_56t="n"
			;;
		
		"-d45b_56t" | "-d45b")
			diag_45b_56t="y"
			diag_45t_56b="n"
			diag_combined="n"
			;;
		
		"-d45t_56b" | "-d45t")
			diag_45b_56t="n"
			diag_45t_56b="y"
			diag_combined="n"
			;;

		"-dboth")
			diag_45b_56t="y"
			diag_45t_56b="y"
			diag_combined="n"
			;;

		"-dc" | "-dcomb")
			diag_45b_56t="n"
			diag_45t_56b="n"
			diag_combined="y"
			;;

		"-danti")
			diag_45b_56t="n"
			diag_45t_56b="n"
			diag_combined="n"
			diag_45b_56b="y"
			diag_45t_56t="y"
			;;

		"-O")
			shift
			run_options="$1"
			;;

		"-no-bckg")
			runInBackground="n"
			;;

		*)
			if [ ! -d "$1" ]
			then
				if [ -s "$1" ]
				then
					src_file="$1"
				else
					echo "ERROR: '$1' is neither source file, neither directory neither parameter."
					PrintUsage
					exit 1
				fi
			else
				if [ "$src_file" == "" ]
				then
					echo "ERROR: source file not defined, skipping directory '$1'."
				else
					if [ "$runInBackground" == "y" ]
					then
						RunOneDir "$src_file" "$1" "1" "$run_options" &
					else
						RunOneDir "$src_file" "$1" "1" "$run_options"
					fi
				fi
			fi
			;;
	esac

	shift
done
